services:
  network-backend-service:
    networks:
      - backend

  microservice-base-service:
    extends:
      service: network-backend-service
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    volumes:
      - ../observability/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-javaagent.jar
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none

  microservice-config-service:
    extends:
      service: microservice-base-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
      - SPRING_PROFILES_ACTIVE=default

  microservice-eureka-service:
    extends:
      service: microservice-config-service
    environment:
      - SPRING_EUREKA_SERVER=eurekaserver

  microservice-application-service:
    extends:
      service: microservice-eureka-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres