version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-ms
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-backend-service

  configserver:
    image: adityaval317/config-server:${BUILD_VERSION:-s8}
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-service

  eurekaserver:
    image: adityaval317/eureka-server:${BUILD_VERSION:-s8}
    container_name: eureka-server-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
    extends:
      file: common-config.yml
      service: microservice-config-service


  accounts:
    image: adityaval317/accounts:${BUILD_VERSION:-s8}
    container_name: accounts-ms
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=accounts
    extends:
      file: common-config.yml
      service: microservice-application-service

  loans:
    image: adityaval317/loans:${BUILD_VERSION:-s8}
    container_name: loans-ms
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:8090/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8090:8090"
    environment:
      - SPRING_APPLICATION_NAME=loans
    extends:
      file: common-config.yml
      service: microservice-application-service

  cards:
    image: adityaval317/cards:${BUILD_VERSION:-s8}
    container_name: cards-ms
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent http://localhost:9000/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "9000:9000"
    environment:
      - SPRING_APPLICATION_NAME=cards
    extends:
      file: common-config.yml
      service: microservice-application-service

  gatewayserver:
    image: adityaval317/gateway-server:${BUILD_VERSION:-s8}
    container_name: gateway-server-ms
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    ports:
      - "8072:8072"
    environment:
      - SPRING_APPLICATION_NAME=gateway-server
    extends:
      file: common-config.yml
      service: microservice-eureka-service

networks:
  backend:
    driver: bridge