apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
  SPRING_EUREKA_SERVER: "eureka-server"
  CONFIGSERVER_APPLICATION_NAME: "config-server"
  EUREKASERVER_APPLICATION_NAME: "eureka-server"
  ACCOUNTS_APPLICATION_NAME: "accounts"
  LOANS_APPLICATION_NAME: "loans"
  CARDS_APPLICATION_NAME: "cards"
  GATEWAY_APPLICATION_NAME: "gateway-server"
  NOTIFICATIONS_APPLICATION_NAME: "notifications"
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
