apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name : accounts
          image: adityaval317/accounts:14
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: ACCOUNTS_APPLICATION_NAME
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: SPRING_CONFIG_IMPORT
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_EUREKA_SERVER
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: SPRING_EUREKA_SERVER
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: microservices-config
                key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080

